language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install lcov rubygems
  - gem install lcoveralls
install: DEBUG=1 make
script:
  - wget http://pjreddie.com/media/files/yolo.weights && ./darknet yolo test cfg/yolo.cfg yolo.weights data/dog.jpg
after_success:
  - lcov -c -d . -o coverage.info
  - lcoveralls coverage.info
