language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install lcov rubygems valgrind
  - gem install lcoveralls
install: DEBUG=1 make
script:
  - wget http://pjreddie.com/media/files/yolo.weights && ./darknet yolo test cfg/yolo.cfg yolo.weights data/dog.jpg
  - DEBUG=1 make check
after_success:
  - lcov -c -d obj -b `pwd` --no-external -o coverage.info 
  - lcoveralls -r . coverage.info
