language: c
compiler:
  - gcc
  - clang
before_install:
  - gem install coveralls-lcov
install: DEBUG=1 make
before_script:
  - lcov --directory . --zerocounters
script:
  - wget http://pjreddie.com/media/files/yolo.weights && ./darknet yolo test cfg/yolo.cfg yolo.weights data/dog.jpg
after_success:
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info # filter out system and test code
  - lcov --list coverage.info # debug before upload
  - coveralls-lcov --repo-token ${COVERALLS_REPO_TOKEN} coverage.info # uploads to coveralls
